# Generated by Django 5.2.5 on 2025-09-12 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Колір фону')),
                ('text_color', models.CharField(default='#000000', max_length=7, verbose_name='Колір тексту')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/', verbose_name='Фонове зображення')),
                ('background_mode', models.CharField(choices=[('cover', 'На весь екран'), ('tile', 'Плитка (2000-і)'), ('dim', 'Затемнене фото')], default='cover', max_length=20)),
                ('font_family', models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Tahoma', 'Tahoma'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Monospace', 'Monospace')], default='Arial', max_length=100, verbose_name='Шрифт')),
                ('custom_css', models.TextField(blank=True, verbose_name='Кастомний CSS')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системна тема')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна тема')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('css_file', models.FileField(blank=True, null=True, upload_to='themes/css/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
