# Generated by Django 5.2.5 on 2025-09-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='text_color',
        ),
    ]
