# Generated by Django 5.2.5 on 2025-08-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='themes/css/'),
        ),
    ]
