# Generated by Django 5.2.5 on 2025-09-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_remove_theme_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='background_mode',
        ),
    ]
