# Generated by Django 5.2.5 on 2025-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_alter_theme_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='css_file',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='tags',
        ),
        migrations.AddField(
            model_name='theme',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='themes/backgrounds/', verbose_name='Фонове зображення'),
        ),
        migrations.AddField(
            model_name='theme',
            name='custom_css',
            field=models.TextField(blank=True, verbose_name='Кастомний CSS'),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New')], default='Arial', max_length=100, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Колір тексту'),
        ),
    ]
