# Generated by Django 5.2.5 on 2025-09-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_remove_theme_background_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AddField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Primary color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Secondary color'),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Колір тексту'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='themes/css/', verbose_name='Generated CSS'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_family',
            field=models.CharField(blank=True, default='Arial', max_length=200, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
