# Generated by Django 5.2.5 on 2025-08-30 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_remove_theme_created_at_remove_theme_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='themes/css/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна тема'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Схвалено'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва теми'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Місткість'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
    ]
