# Generated by Django 5.2.4 on 2025-09-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_alter_theme_options_theme_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={},
        ),
        migrations.AlterField(
            model_name='theme',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='themes/css/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Tahoma', 'Tahoma'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Monospace', 'Monospace')], default='Arial', max_length=100, verbose_name='Шрифт'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Основний колір'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#666666', max_length=7, verbose_name='Другорядний колір'),
        ),
    ]
