# Generated by Django 5.2.4 on 2025-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_theme_created_by_theme_css_file_theme_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
