# Generated by Django 5.2.5 on 2025-09-01 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_alter_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
