# Generated by Django 5.2.5 on 2025-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_alter_theme_created_at_alter_theme_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
