# Generated by Django 5.2.5 on 2025-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_alter_theme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Tahoma', 'Tahoma'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Monospace', 'Monospace')], default='Arial', max_length=100, verbose_name='Шрифт'),
        ),
    ]
