# Generated by Django 5.2.5 on 2025-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0010_alter_theme_font_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='extra_css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
