# Generated by Django 5.2.5 on 2025-09-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0011_remove_theme_description_theme_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='extra_css',
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
