# Generated by Django 5.2.4 on 2025-09-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0012_remove_theme_bg_color_remove_theme_extra_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='css_file',
        ),
    ]
