# Generated by Django 5.2.5 on 2025-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0013_remove_theme_css_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='themes/css/'),
        ),
    ]
