# Generated by Django 5.2.5 on 2025-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0014_theme_css_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_mode',
            field=models.CharField(choices=[('cover', 'На весь екран'), ('tile', 'Плитка (2000-і)'), ('dim', 'Затемнене фото')], default='cover', max_length=20),
        ),
    ]
