# Generated by Django 5.2.5 on 2025-09-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0015_theme_background_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='theme',
        ),
        migrations.AddField(
            model_name='theme',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системна тема'),
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
