# Generated by Django 5.2.5 on 2025-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_galleryitem_file_galleryitem_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
