# Generated by Django 5.2.5 on 2025-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryitem_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitem',
            old_name='uploaded_by',
            new_name='uploader',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
