# Generated by Django 5.2.4 on 2025-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_uploaded_by_galleryitem_uploader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='age_rating',
            field=models.CharField(choices=[('e', 'Everyone'), ('t', 'Teen'), ('m', 'Mature'), ('a', 'Adults Only')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gallery.tag'),
        ),
    ]
