# Generated by Django 5.2.5 on 2025-09-13 08:28

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_tag_galleryitem_age_rating_galleryitem_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
