# Generated by Django 5.2.5 on 2025-09-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва уроку')),
                ('datetime', models.DateTimeField(verbose_name='Дата Уроку')),
            ],
        ),
        migrations.CreateModel(
            name='Logik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оцінка')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronicdiary.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учень')),
            ],
        ),
    ]
