# Generated by Django 5.2.5 on 2025-08-30 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='Запитання'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Відповідь'),
        ),
        migrations.AlterField(
            model_name='question',
            name='page_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Сторінка питання'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Запитання', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=250, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Створенно: '),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='discription',
            field=models.CharField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.TextField(max_length=200, verbose_name="Ім'я тестування"),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Питання'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answeroption', verbose_name='Вибранна відповідь'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Тестування'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Відповідь користувача'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
