# Generated by Django 5.2.5 on 2025-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='опис категорії'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='назва категорії'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_text',
            field=models.TextField(verbose_name='текст контенту'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='theme',
            field=models.CharField(max_length=300, verbose_name='тема обговорення'),
        ),
    ]
