# Generated by Django 5.2.5 on 2025-08-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thread_ids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
