# Generated by Django 5.2.5 on 2025-08-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_category_id_post_thread_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thread_ids',
        ),
    ]
