# Generated by Django 5.2.5 on 2025-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_post_category_id_remove_post_thread_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url_thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
