# Generated by Django 5.2.5 on 2025-09-13 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_url_category_id_post_url_thread_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField(verbose_name='текст контенту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('files', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('url_thread_id', models.IntegerField(blank=True, null=True)),
                ('url_category_id', models.IntegerField(blank=True, null=True)),
                ('url_post_id', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
            ],
        ),
    ]
