# Generated by Django 5.2.5 on 2025-09-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_replypost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replypost',
            name='url_category_id',
        ),
        migrations.RemoveField(
            model_name='replypost',
            name='url_thread_id',
        ),
    ]
