# Generated by Django 5.2.5 on 2025-09-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_replypost_url_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replypost',
            name='url_post_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.thread'),
        ),
        migrations.AlterField(
            model_name='replypost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_posts', to='forum.post'),
        ),
    ]
