# Generated by Django 5.2.5 on 2025-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_replypost_url_post_id_alter_post_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='replypost',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='reply_post/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thread'),
        ),
    ]
