# Generated by Django 5.2.5 on 2025-09-12 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Локація')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workshops', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Воркшоп',
                'verbose_name_plural': 'Воркшопи',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('file', models.FileField(upload_to='gallery/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео')], default='image', max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Елемент галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_at'],
            },
        ),
    ]
