# Generated by Django 5.2.5 on 2025-08-24 08:46

import django.db.models.deletion
import workshops.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Теми',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Кінець')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Локація')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість місць')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Воркшоп',
                'verbose_name_plural': 'Воркшопи',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file', models.FileField(upload_to=workshops.models.gallery_upload_path, verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео'), ('file', 'Файл')], default='image', max_length=10, verbose_name='Тип медіа')),
                ('approved', models.BooleanField(default=False, verbose_name='Схвалено модератором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='workshops.theme', verbose_name='Тема')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='workshops.workshop', verbose_name='Воркшоп')),
            ],
            options={
                'verbose_name': 'Елемент галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_at'],
            },
        ),
    ]
