# Generated by Django 5.2.5 on 2025-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=20, verbose_name='Колір фону'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/backgrounds/', verbose_name='Фонове зображення'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='custom_css',
            field=models.TextField(blank=True, verbose_name='Користувацький CSS'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='font_family',
            field=models.CharField(blank=True, default='Arial', max_length=100, verbose_name='Шрифт'),
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
    ]
