# Generated by Django 5.2.4 on 2025-09-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_workshop_background_color_workshop_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='font_family',
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('file', models.FileField(upload_to='gallery/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео')], default='image', max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Елемент галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_at'],
            },
        ),
    ]
