# Generated by Django 5.2.5 on 2025-09-12 17:56

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Світла'), ('dark', 'Темна')], default='light', max_length=20)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Біо')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_path, verbose_name='Аватар')),
                ('custom_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='themes.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
