# Generated by Django 5.2.5 on 2025-08-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Світла'), ('dark', 'Темна')], default='light', max_length=20),
        ),
    ]
