# Generated by Django 5.2.5 on 2025-09-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar_profile_bio'),
        ('themes', '0009_alter_theme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='themes.theme'),
        ),
    ]
