# Generated by Django 5.2.5 on 2025-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speciality',
            field=models.CharField(choices=[('низька', 'низька'), ('середня', 'середня'), ('висока', 'висока'), ('дуже висока', 'дуже висока')], default='-', verbose_name='Важливість події'),
        ),
    ]
