# Generated by Django 5.2.5 on 2025-09-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Варіант'),
        ),
        migrations.AlterField(
            model_name='option',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting_system.voting', verbose_name='Голосування'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Зробленно в '),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_votes', to='voting_system.option', verbose_name='Вибір голосування'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL, verbose_name='Голосування людей'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_votes', to='voting_system.voting', verbose_name='Збереження голосовань'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_voting', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено в '),
        ),
        migrations.AlterField(
            model_name='voting',
            name='data_end',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець голосування'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='data_start',
            field=models.DateField(blank=True, null=True, verbose_name='Початок голосування'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва голосування'),
        ),
    ]
