# Generated by Django 5.2.1 on 2025-08-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('fille', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('yt_url', models.CharField(max_length=80)),
                ('creater', models.CharField(max_length=30)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('Update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
