# Generated by Django 5.2.5 on 2025-08-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fille',
            field=models.FileField(null=True, upload_to='material/file'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(null=True, upload_to='material/image'),
        ),
        migrations.AlterField(
            model_name='material',
            name='yt_url',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
