# Generated by Django 5.2.5 on 2025-08-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_material_fille_alter_material_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fille',
            field=models.FileField(blank=True, null=True, upload_to='material/file'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='material/image'),
        ),
        migrations.AlterField(
            model_name='material',
            name='yt_url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
