# Generated by Django 5.2.5 on 2025-08-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_material_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='creater',
            new_name='creator',
        ),
    ]
