# Generated by Django 5.2.5 on 2025-08-30 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_rename_creater_material_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='fille',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='Update_time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='material',
            name='advert_id',
        ),
        migrations.AlterField(
            model_name='material',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='yt_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
