# Generated by Django 5.2.5 on 2025-09-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_rename_fille_material_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='material',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='material/file', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='material/image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час оновлення'),
        ),
        migrations.AlterField(
            model_name='material',
            name='yt_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Посилання ют'),
        ),
    ]
